### ISSUE TITLE
Installing JSmooth-0.9.9-7-setup fails

### ISSUE THREAD

**Issue by OusJallow** [BisonSchweizAG/JSmooth#1]
Installing [jsmooth-0.9.9-7-setup](https://sourceforge.net/projects/jsmooth/files/latest/download)  on a Windows 10  v1809 (x64) fails. Previously, I have successfully installed jsmooth-0.9.9-7 on a Windows10 with v16xx I think. After reinstalling Windows and upgrading to v1809, installation fails. 

I have redownloaded the setup a couple of times with the same results. 

Here are some screen shots below:

![Installation Screen](https://github.com/OusJallow/Link-Resources/raw/master/window.PNG)

![Error Screen](https://raw.githubusercontent.com/OusJallow/Link-Resources/master/jsmooth-stop.PNG)

**Comment by OusJallow** [comment]
Downloaded and extracted [jsmooth-0.9.11](https://github.com/BisonSchweizAG/JSmooth/releases/download/v0.9.11/jsmooth-0.9.11.zip) from repo releases. Working fine. Thanks.

**Comment by reinhapa** [comment]
@OusJallow thanks for the feedback
